
kind: PersistentVolume
apiVersion: v1
metadata:
  name: elk-pv
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/disk/vol1"

