
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elk-pv-claim
  namespace: logging
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
