
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: standard
  namespace: logging
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---


kind: PersistentVolume
apiVersion: v1
metadata:
  name: elk-pv
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/disk/vol1"

